spring.application.name=backend
# ----------------------------------------
# PostgreSQL Database
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/swing_engine
spring.datasource.username=postgres
spring.datasource.password=7733
spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------------------
# JPA / Hibernate
# ----------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ----------------------------------------
# Logging
# ----------------------------------------
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ----------------------------------------
# Server
# ----------------------------------------
server.port=8080
#----------------------------------------
# Application Mode
#----------------------------------------
application.mode=LOAD_DAILY_PRICES
#LOAD_NIFTY500
# ==========================
# Market Data
# ==========================
marketdata.nifty500-url=https://www.niftyindices.com/IndexConstituent/ind_nifty500list.csv
marketdata.yahoo.base-url=https://query1.finance.yahoo.com
marketdata.yahoo.chart-endpoint=/v8/finance/chart/
#-----------------------------------------

spring.profiles.active=local
